routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes(['verify' => true]);
Route::middleware(['auth'])->group(function () {
    Route::get('/password/expired/', 'Auth\ExpiredPasswordController@showResetForm')->name('password.expired.form');
    Route::post('/password/expired/', 'Auth\ExpiredPasswordController@reset')->name('password.expired.reset');
});

Route::get('/', 'HomeController@index')->name('home');
Route::get('/search', 'SearchController@search')->name('search');

/*
 * Auth
 */
Route::resource('users', 'UserController')->only(['show']);

Route::get('/two-factor', 'Auth\LoginController@show2faForm')->name('2fa.validate.form');
Route::post('/two-factor', 'Auth\LoginController@validate2fa')->name('2fa.validate');
Route::get('/two-factor/recovery', 'Auth\LoginController@showRecoveryForm')->name('2fa.recovery.form');
Route::post('/two-factor/recovery', 'Auth\LoginController@recover')->name('2fa.recovery');

/*
 * SSO
 */
if (config('auth.single_sign_on.enabled')) {
    Route::get('/connect/{provider}', 'Auth\LoginController@redirectToProvider')->name('sso.redirect');
    Route::get('/connect/{provider}/callback', 'Auth\LoginController@handleProviderCallback')->name('sso.callback');
}

/*
 * Media
 */

Route::get('/medias/{media}/', 'MediaController@show')->name('medias.show');

/*
 * Settings
 */
Route::prefix('settings')->group(function () {
    Route::get('/profile', 'SettingsController@profile')->name('settings.profile');
    Route::patch('/profile', 'SettingsController@updateProfile')->name('settings.profile.update');
    Route::get('/password', 'SettingsController@password')->name('settings.password');
    Route::patch('/password', 'SettingsController@updatePassword')->name('settings.password.update');
    Route::get('/security', 'SettingsController@security')->name('settings.security');
    Route::get('/personal_access_tokens', 'SettingsController@accessTokens')->name('settings.access-tokens');
    Route::get('/applications', 'SettingsController@applications')->name('settings.applications');

    if (config('auth.single_sign_on.enabled')) {
        Route::post('/accounts/{provider}/disconnect', 'SettingsController@disconnectAccount')
            ->name('settings.accounts.disconnect');
    }

    Route::get('/security/otp/setup', 'SettingsController@setupOtp')->name('settings.otp.setup');
    Route::post('/security/otp/setup', 'SettingsController@validateOtpSetup')->name('settings.otp.validate');
    Route::post('/security/otp/codes', 'SettingsController@regenerateOtpRecoveryCodes')->name('settings.otp.codes');
    Route::post('/security/otp/disable', 'SettingsController@disableOtp')->name('settings.otp.disable');
});

/*
 * Repositories & packages
 */

Route::resource('repos', 'RepositoryController');
Route::get('/r/{key}', 'RepositoryController@showWithKey')->name('repos.show.key');
Route::get('/repos/{repo}/members', 'RepositoryController@showMembers')->name('repos.members.show');
Route::post('/repos/{repo}/members', 'RepositoryController@addMembers')->name('repos.members.add');


Route::resource('packages', 'PackageController')->except(['create', 'store']);
Route::get('/packages/{package}/files/', 'PackageController@browseFile')->name('packages.files');
Route::get('/packages/{package}/versions/', 'PackageController@showVersions')->name('packages.versions');
Route::get('/packages/{package}/builds/', 'PackageController@showBuilds')->name('packages.builds');
Route::get('/packages/{package}/builds/{build}', 'PackageController@showBuild')->name('packages.build');

app/Models/Group.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Group extends Model
{
    /*
     * Relationships
     */

    public function avatar()
    {
        return $this->belongsTo(Media::class, 'avatar_id');
    }

    /*
     * Accessors & mutators
     */

    public function getAvatarUrlAttribute()
    {
        if ($this->avatar) {
            return $this->avatar->url;
        } else {
            return asset('images/organization-avatar.png');
        }
    }
}

app/Models/PackageVersion.php
<?php

namespace App\Models;

use App\Conan\PackageVersionReference;
use App\Conan\Paths;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

/**
 * @method static PackageVersion findOrFail(int $packageVersionId)
 */
class PackageVersion extends Model
{
    protected $fillable = ['version_string', 'channel'];

    /*
     * Relationships
     */

    public function package()
    {
        return $this->belongsTo(Package::class);
    }

    public function builds()
    {
        return $this->hasMany(PackageBuild::class);
    }

    /*
     * Accessors & mutators
     */

    public function getFolderPathAttribute()
    {
        return Paths::PACKAGES_FOLDER."/".$this->id;
    }

    public function getRecipeFolderPathAttribute()
    {
        return $this->folderPath."/".Paths::RECIPE_FOLDER;
    }

    public function getReferenceAttribute()
    {
        return new PackageVersionReference(
            $this->package->name,
            $this->version_string,
            $this->package->user,
            $this->channel
        );
    }

    public function getFilesAttribute()
    {
        return Storage::allFiles($this->recipeFolderPath);
    }

    // TODO: optimization
    public function getHasWindowsBuildAttribute()
    {
        return $this->builds()->whereIn('os', ['Windows', 'WindowsStore'])->count() > 0;
    }

    public function getHasLinuxBuildAttribute()
    {
        return $this->builds()->where('os', 'Linux')->count() > 0;
    }

    public function getHasAppleBuildAttribute()
    {
        return $this->builds()->whereIn('os', ['Macos', 'iOS', 'watchOS', 'tvOS'])->count() > 0;
    }

    public function getHasAndroidBuildAttribute()
    {
        return $this->builds()->where('os', 'Android')->count() > 0;
    }

    public function getHasFreeBSDBuildAttribute()
    {
        return $this->builds()->where('os', 'FreeBSD')->count() > 0;
    }

    public function getHasArduinoBuildAttribute()
    {
        return $this->builds()->where('os', 'Arduino')->count() > 0;
    }
}

app/Models/Repository.php
<?php

namespace App\Models;

use App\Conan\PackageVersionReference;
use App\Enums\VisibilityType;
use App\Models\Traits\HasAvatar;
use Illuminate\Database\Eloquent\Model;

/**
 * @method static Repository findOrFail(int $repositoryId)
 * @method static bool exists(int $repository)
 */
class Repository extends Model
{
    use HasAvatar;

    protected $fillable = ['name', 'path', 'description'];

    public function owner()
    {
        return $this->morphTo();
    }

    public function packages()
    {
        return $this->hasMany(Package::class);
    }

    public function avatar()
    {
        return $this->belongsTo(Media::class, 'avatar_id');
    }

    public function members()
    {
        return $this->belongsToMany(User::class, 'repository_memberships')
            ->using(RepositoryMembership::class);
    }

    /*
     * Helpers
     */

    public function defaultAvatarUrl()
    {
        return asset('images/repo-avatar.png');
    }

    public function getPackageVersion(PackageVersionReference $reference) : PackageVersion
    {
        $package = $this->packages()->where([
            'name' => $reference->name(),
            'user' => $reference->user()
        ])->firstOrFail();

        $packageVersion = $package->versions()->where([
            'version_string' => $reference->version(),
            'channel' => $reference->channel()
        ])->firstOrFail();

        return $packageVersion;
    }

    public function getOrCreatePackageVersion(PackageVersionReference $reference) : PackageVersion
    {
        $package = $this->packages()->firstOrCreate([
            'name' => $reference->name(),
            'user' => $reference->user()
        ], [
            'visibility' => VisibilityType::PUBLIC
        ]);

        $packageVersion = $package->versions()->firstOrCreate([
            'version_string' => $reference->version(),
            'channel' => $reference->channel()
        ]);

        return $packageVersion;
    }
}

app/Http/Controllers/RepositoryController.php
<?php

namespace App\Http\Controllers;

use App\Enums\VisibilityType;
use App\Http\Requests\RepositoryAddMemberRequest;
use App\Http\Requests\RepositoryStoreRequest;
use App\Http\Requests\RepositoryUpdateRequest;
use App\Models\Group;
use App\Models\Repository;
use App\Models\User;
use Illuminate\Database\Eloquent\Builder as EloquentBuilder;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class RepositoryController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Repository::class, 'repo');
        $this->middleware('can:admin,repo')->only(['showMembers', 'addMembers']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $repos = Repository::where('visibility', VisibilityType::PUBLIC);

        if (Auth::check()) {
            $repos->orWhere(function (EloquentBuilder $query) {
                $query->where('visibility', VisibilityType::PRIVATE)
                    ->where(function (EloquentBuilder $query) {
                        $query->where(function (EloquentBuilder $query) {
                            $query->where('owner_id', Auth::user()->id)
                            ->where('owner_type', User::class);
                        })->orWhere(function (EloquentBuilder $query) {
                            $query->where('owner_type', Group::class); // Check membership
                        });
                    });
            });
        }

        $repos = $repos->paginate(15);

        return view('repositories.index', compact('repos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('repositories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\RepositoryStoreRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RepositoryStoreRequest $request)
    {
        $repo = new Repository($request->input());
        $repo->visibility = $request->input('visibility') == "public" ?
            VisibilityType::PUBLIC :
            VisibilityType::PRIVATE;
        $repo->owner()->associate($request->user());

        if ($repo->description === null) {
            $repo->description = '';
        }

        $repo->save();

        return redirect()->route('repos.show.key', $repo->path);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Repository  $repo
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, Repository $repo)
    {
        $packages = $repo->packages()->where('visibility', VisibilityType::PUBLIC);
        if (Auth::check() && $request->user()->can('read', $repo)) {
            $packages->orWhere('visibility', VisibilityType::PRIVATE);
        }
        $packages = $packages->paginate(12);

        return view('repositories.show', compact('repo', 'packages'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Repository  $repo
     * @return \Illuminate\Http\Response
     */
    public function showWithKey(Request $request, string $key)
    {
        $repo = Repository::where('path', $key)->firstOrFail();
        $this->authorize('view', $repo);

        return $this->show($request, $repo);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Repository  $repo
     * @return \Illuminate\Http\Response
     */
    public function edit(Repository $repo)
    {
        return view('repositories.edit', compact('repo'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\RepositoryUpdateRequest  $request
     * @param  \App\Models\Repository  $repo
     * @return \Illuminate\Http\Response
     */
    public function update(RepositoryUpdateRequest $request, Repository $repo)
    {
        $repo->name = $request->get('name', '');
        if ($repo->name == null) {
            $repo->name = '';
        }

        $repo->description = $request->get('description', '');
        if ($repo->description == null) {
            $repo->description = '';
        }

        $repo->visibility = $request->get('visibility');

        $repo->addAvatarFromRequest();

        $repo->save();

        return redirect()->route('repos.show', $repo);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Repository  $repo
     * @return \Illuminate\Http\Response
     */
    public function destroy(Repository $repo)
    {
        $repo->delete();
        return redirect()->route('home');
    }

    /*
     * Members
     */

    /**
     * @param  \App\Models\Repository  $repo
     * @return \Illuminate\Http\Response
     */
    public function showMembers(Request $request, Repository $repo)
    {
        $members = $repo->members()->sort();

        if ($request->has('search')) {
            $members->where('name', 'like', '%'.$request->input('search').'%');
        }

        $members = $members->paginate(50);

        return view('repositories.members', compact('repo', 'members'));
    }

    /**
     * @param  \App\Http\Requests\RepositoryAddMemberRequest  $request
     * @param  \App\Models\Repository  $repo
     * @return \Illuminate\Http\Response
     */
    public function addMembers(RepositoryAddMemberRequest $request, Repository $repo)
    {
        $repo->members()->attach($request->input('user_ids'), [
            'expired_at' => $request->input('expires_at') ?: null,
            'permission_type' => $request->input('permission_level')
        ]);

        return redirect()->route('repos.members.show', $repo);
    }
}

resources/views/repositories/create.blade.php
@extends('layouts.main')

@section('main-content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-3">
                <h4>New repository</h4>
                <p>
                    A project is where you house your packages, plan your work (issues), and publish your
                    documentation (wiki), among other things.
                </p>
                <p>
                    All features are enabled for blank projects, from templates, or when importing, but you can disable
                    them afterward in the project settings.
                </p>
            </div>
            <div class="col-lg-9">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <form action="{{ route('repos.store') }}" method="post" class="card">
                    @csrf
                    <div class="card-header">Header</div>
                    <div class="card-body">
                        <div class="form-row">
                            <div class="form-group col-xl-6 mb-xl-0">
                                <label for="name-input">Name</label>
                                <input type="text" class="form-control" id="name-input" placeholder="My repository"
                                       name="name" required>
                            </div>
                            <div class="form-group col-xl-6 mb-0">
                                <label for="path-input">Path</label>
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">{{ route('repos.show.key', '') }}/</span>
                                    </div>
                                    <input type="text" class="form-control" id="path-input" name="path" placeholder="my-repository"
                                           title="Please choose a group path with no special characters."
                                           pattern="[a-zA-Z0-9_\.][a-zA-Z0-9_\-]*" required>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="desc-input">Description (optional)</label>
                            <textarea name="description" class="form-control" rows="3" id="desc-input" placeholder="Description"></textarea>
                        </div>
                        <label for="a">Visibility</label>
                        <div class="form-group">
                            <div class="form-check mb-2">
                                <input class="form-check-input" type="radio" name="visibility" id="visibility-public" value="public" checked>
                                <label for="visibility-public" class="form-check-label">
                                    <span class="d-block">Public</span>
                                    <span class="d-block form-text text-muted mt-0">The repository can be accessed without any authentication.</span>
                                </label>
                            </div>
                            <div class="form-check mb-2">
                                <input class="form-check-input" type="radio" name="visibility" id="visibility-private" value="private">
                                <label for="visibility-private" class="form-check-label">
                                    <span class="d-block">Private</span>
                                    <span class="d-block form-text text-muted mt-0">Access must be granted explicitly to each user.</span>
                                </label>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-success">Create</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/repositories/edit.blade.php
@extends('layouts.main')

@section('main-content')
    <div class="container-fluid">
        @include('repositories.partials.navbar')
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <form action="{{ route('repos.update', $repo) }}" method="post" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="card col-12 p-0 mb-4">
                <div class="card-body row ml-1 mr-1">
                    <div class="col-md-9 pl-0">
                        <div class="media">
                            <avatar-image-input class="mr-3 avatar" name="avatar" src="{{ $repo->avatarUrl }}"></avatar-image-input>
                            <div class="media-body">
                                <input type="text" class="form-control mb-2" name="name" value="{{ $repo->name }}">
                                <textarea class="form-control" placeholder="Description" name="description"
                                          rows="4" maxlength="1000">{{ $repo->description }}</textarea>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 pl-0">
                        <button type="submit" class="btn btn-success btn-lg btn-block">@lang('packages.update')</button>
                        <button type="button" class="btn btn-danger btn-lg btn-block" data-toggle="modal" data-target="#deleteModal">Delete</button>
                        <a href="{{ route('repos.show', $repo) }}" class="btn btn-outline-danger btn-lg btn-block">Cancel</a>
                    </div>
                </div>
            </div>
            <div class="card col-12 p-0 mb-4">
                <div class="card-header" id="permissions-panel-header">
                    <div class="d-flex bd-highlight mb-0">
                        <h3 class="mb-0">
                            Permissions
                        </h3>
                        <button class="btn ml-auto" type="button" data-toggle="collapse" data-target="#permissions-panel"
                                aria-expanded="true" aria-controls="permissions-panel">
                            Expand
                        </button>
                    </div>
                </div>
                <div id="permissions-panel" class="collapse" aria-labelledby="permissions-panel-header">
                    <div class="card-body">
                        <fieldset>
                            <h4>Visibility</h4>
                            <div class="form-group">
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="visibility" id="public-visibility"
                                           value="{{ \App\Enums\VisibilityType::PUBLIC }}" @if($repo->visibility == \App\Enums\VisibilityType::PUBLIC) checked @endif>
                                    <label class="form-check-label" for="public-visibility">Public</label>
                                </div>
                                <small id="passwordHelpBlock" class="form-text text-muted">
                                    The repository can be accessed by anyone, regardless of authentication.
                                </small>
                            </div>
                            <div class="form-group mb-0">
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="visibility" id="private-visibility"
                                           value="{{ \App\Enums\VisibilityType::PRIVATE }}" @if($repo->visibility == \App\Enums\VisibilityType::PRIVATE) checked @endif>
                                    <label class="form-check-label" for="private-visibility">Private</label>
                                </div>
                                <small id="passwordHelpBlock" class="form-text text-muted">
                                    The repository is accessible only by members. Access must be granted explicitly to each user.
                                </small>
                            </div>
                        </fieldset>
                    </div>
                </div>
            </div>
        </form>
        <deletion-modal id="deleteModal" name="{{ $repo->path }}" action="{{ route('repos.destroy', $repo) }}"></deletion-modal>
    </div>
@endsection

resources/views/repositories/index.blade.php
@extends('layouts.main')

@section('main-content')
    <h1>Repositories</h1>
    <nav class="navbar navbar-dark bg-conan">
        <ul class="nav nav-pills">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Features</a>
            </li>
        </ul>
        <form class="form-inline">
            <input class="form-control mr-sm-2" type="search" placeholder="Filter by name..." aria-label="Search">
            <select name="" id="" class="form-control">
                <option value="">aa</option>
            </select>
            <a href="{{ route('repos.create') }}" class="btn btn-success">Create repository</a>
        </form>
    </nav>
    <table class="table">
        @foreach($repos as $repo)
            <tr>
                <td class="media">
                    <img class="mr-3 avatar-sm" src="{{ $repo->avatar_url }}" alt="Generic placeholder image">
                    <div class="media-body d-flex">
                        <div>
                            <h4 class="mb-0"><a href="{{ route('repos.show.key', $repo->path) }}">{{ $repo->name }}</a></h4>
                            {{ $repo->description }}
                        </div>
                        <div class="ml-auto text-right">
                            <div>
                                @include('repositories.partials.visibility-icon')
                            </div>
                            <div>Updated {{ $repo->updated_at->diffForHumans(\Carbon\Carbon::now()) }}</div>
                        </div>
                    </div>
                </td>
            </tr>
        @endforeach
    </table>
    {{ $repos->links() }}
@endsection

resources/views/repositories/members.blade.php
@extends('layouts.main')

@section('main-content')
    <div class="container-fluid">
        @include('repositories.partials.navbar')
        @include('repositories.partials.header')

        <div class="card col-12 p-0 mb-4">
            <h3 class="card-header">Invite members</h3>
            <div class="card-body">
                <form action="{{ route('repos.members.add', $repo) }}" method="post">
                    @csrf
                    <div class="form-group">
                        <label for="members-select">Select members to invite</label>
                        <member-search-input id="members-select"></member-search-input>
                    </div>
                    <div class="form-group">
                        <label for="role-select">Choose a role permission</label>
                        <select id="role-select" class="form-control" name="permission_level">
                            @foreach(\App\Enums\PermissionType::toSelectArray() as $key => $str)
                                <option value="{{ $key }}">{{ $str }}</option>
                            @endforeach
                        </select>
                        <small class="form-text text-muted">Read more about role permissions</small>
                    </div>
                    <div class="form-group">
                        <label for="expiration-date-input">Access expiration date</label>
                        <input type="date" class="form-control" id="expiration-date-input" placeholder="Expiration date" name="expires_at">
                    </div>
                    <button type="submit" class="btn btn-success">Add to repository</button>
                </form>
            </div>
        </div>
        <div class="card col-12 p-0 mb-4">
            <div class="card-header d-flex">
                <h3>Members of {{ $repo->name }} <span class="badge badge-secondary">{{ $members->total() + 1 }}</span></h3>
                <form class="form-inline ml-auto">
                    <div class="input-group mr-2">
                        <input type="text" class="form-control" placeholder="Find existing members by name" name="search" value="{{ request('search') }}">
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary" type="submit"><i class="fas fa-search"></i></button>
                        </div>
                    </div>

                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                            Sort
                        </button>
                        <div class="dropdown-menu dropdown-menu-right">
                            <h6 class="dropdown-header">Sort by</h6>
                            <a class="dropdown-item" href="{{ url()->current().'?'. http_build_query(['sort' => sortable_parameter('name', \App\Enums\OrderType::ASC) ] + request()->query()) }}">Name, ascending</a>
                            <a class="dropdown-item" href="{{ url()->current().'?'. http_build_query(['sort' => sortable_parameter('name', \App\Enums\OrderType::DESC) ] + request()->query()) }}">Name, descending</a>
                        </div>
                    </div>
                </form>
            </div>
            <div class="card-body">
                <table class="table mb-0">
                    <tr>
                        <td class="media">
                            <img class="mr-3 avatar-sm" src="{{ $repo->owner->avatar_url }}" alt="Generic placeholder image">
                            <div class="media-body d-flex">
                                <div>
                                    <a href="{{ route('users.show', $repo->owner) }}">{{ $repo->owner->name }}</a>
                                </div>
                                <div class="ml-auto text-right">
                                    <div>Owner</div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    @foreach($members as $member)
                        <tr>
                            <td class="media">
                                <img class="mr-3 avatar-sm" src="{{ $member->avatar_url }}" alt="Generic placeholder image">
                                <div class="media-body d-flex">
                                    <div>
                                        <a href="{{ route('users.show', $member) }}">{{ $member->name }}</a>
                                    </div>
                                    <div class="ml-auto text-right">
                                        <div>{{ \App\Enums\PermissionType::getDescription($member->pivot->permission_type) }}</div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                </table>
                {{ $members->links() }}
            </div>
        </div>
    </div>
@endsection

resources/views/repositories/show.blade.php
@extends('layouts.main')

@section('main-content')
    <div class="container-fluid">
        @include('repositories.partials.navbar')
        @include('repositories.partials.header')
        {{ $packages->links() }}
        <div class="row">
            @foreach($packages as $package)
                <div class="col-xs-12 col-lg-6 col-xl-4">
                    <div class="card rounded-0 package-box">
                        <div class="card-body d-flex">
                            <div>
                                <a href="{{ route('packages.show', $package) }}" class="d-block h5"><b>{{ $package->name }}</b> : {{ $package->user }}</a>
                                <p class="mb-0">
                                    {{ $package->description }}
                                </p>
                            </div>

                            <img class="mr-3 avatar ml-auto" src="{{ $package->avatar_url }}" alt="{{ $package->reference }} package avatar">

                        </div>
                    </div>
                </div>
            @endforeach
        </div>
        {{ $packages->links() }}
    </div>
@endsection