routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes(['verify' => true]);
Route::middleware(['auth'])->group(function () {
    Route::get('/password/expired/', 'Auth\ExpiredPasswordController@showResetForm')->name('password.expired.form');
    Route::post('/password/expired/', 'Auth\ExpiredPasswordController@reset')->name('password.expired.reset');
});

Route::get('/', 'HomeController@index')->name('home');
Route::get('/search', 'SearchController@search')->name('search');

/*
 * Auth
 */
Route::resource('users', 'UserController')->only(['show']);

Route::get('/two-factor', 'Auth\LoginController@show2faForm')->name('2fa.validate.form');
Route::post('/two-factor', 'Auth\LoginController@validate2fa')->name('2fa.validate');
Route::get('/two-factor/recovery', 'Auth\LoginController@showRecoveryForm')->name('2fa.recovery.form');
Route::post('/two-factor/recovery', 'Auth\LoginController@recover')->name('2fa.recovery');

/*
 * SSO
 */
if (config('auth.single_sign_on.enabled')) {
    Route::get('/connect/{provider}', 'Auth\LoginController@redirectToProvider')->name('sso.redirect');
    Route::get('/connect/{provider}/callback', 'Auth\LoginController@handleProviderCallback')->name('sso.callback');
}

/*
 * Media
 */

Route::get('/medias/{media}/', 'MediaController@show')->name('medias.show');

/*
 * Settings
 */
Route::prefix('settings')->group(function () {
    Route::get('/profile', 'SettingsController@profile')->name('settings.profile');
    Route::patch('/profile', 'SettingsController@updateProfile')->name('settings.profile.update');
    Route::get('/password', 'SettingsController@password')->name('settings.password');
    Route::patch('/password', 'SettingsController@updatePassword')->name('settings.password.update');
    Route::get('/security', 'SettingsController@security')->name('settings.security');
    Route::get('/personal_access_tokens', 'SettingsController@accessTokens')->name('settings.access-tokens');
    Route::get('/applications', 'SettingsController@applications')->name('settings.applications');

    if (config('auth.single_sign_on.enabled')) {
        Route::post('/accounts/{provider}/disconnect', 'SettingsController@disconnectAccount')
            ->name('settings.accounts.disconnect');
    }

    Route::get('/security/otp/setup', 'SettingsController@setupOtp')->name('settings.otp.setup');
    Route::post('/security/otp/setup', 'SettingsController@validateOtpSetup')->name('settings.otp.validate');
    Route::post('/security/otp/codes', 'SettingsController@regenerateOtpRecoveryCodes')->name('settings.otp.codes');
    Route::post('/security/otp/disable', 'SettingsController@disableOtp')->name('settings.otp.disable');
});

/*
 * Repositories & packages
 */

Route::resource('repos', 'RepositoryController');
Route::get('/r/{key}', 'RepositoryController@showWithKey')->name('repos.show.key');
Route::get('/repos/{repo}/members', 'RepositoryController@showMembers')->name('repos.members.show');
Route::post('/repos/{repo}/members', 'RepositoryController@addMembers')->name('repos.members.add');


Route::resource('packages', 'PackageController')->except(['create', 'store']);
Route::get('/packages/{package}/files/', 'PackageController@browseFile')->name('packages.files');
Route::get('/packages/{package}/versions/', 'PackageController@showVersions')->name('packages.versions');
Route::get('/packages/{package}/builds/', 'PackageController@showBuilds')->name('packages.builds');
Route::get('/packages/{package}/builds/{build}', 'PackageController@showBuild')->name('packages.build');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="/images/conan.png" />

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Conan Warehouse') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-dark bg-conan">
            <a class="navbar-brand" href="{{ url('/') }}">
                <img src="/images/conan.png" width="30" height="30" alt="">
                {{ config('app.name', 'Conan Warehouse') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <form class="form-inline" action="{{ route('search') }}" method="get">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <button class="btn btn-conan-dark" type="submit"><i class="fas fa-search"></i></button>
                        </div>
                        <input type="text" name="q" class="form-control" placeholder="Search" aria-label="Search">
                    </div>
                </form>
                <ul class="navbar-nav ml-2">
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <li>
                                    <a class="dropdown-item" href="{{ route('users.show', \Auth::id()) }}">Profile</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{{ route('settings.profile') }}">Settings</a>
                                </li>
                                <li class="dropdown-divider"></li>

                                <li>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </li>
                            </ul>
                        </li>
                    @endguest
                    <li class="nav-item">
                        <a class="nav-link" href="#">Help</a>
                    </li>
                </ul>
            </div>
        </nav>

        <main class="content">
            @yield('content')
        </main>

        <footer class="footer">
            <div class="container">
                <span class="text-muted">Place sticky footer content here.</span>
            </div>
        </footer>
    </div>
</body>
</html>

resources/views/layouts/main.blade.php
@extends('layouts.app')

@section('content')
    <div class="sidebar-wrapper">
        <!-- Sidebar  -->
        <nav class="sidebar">
            <ul class="list-unstyled components">
                <li>
                    <a href="#">
                        <i class="fas fa-home"></i> Home
                    </a>
                    <a href="{{ route('repos.index') }}">
                        <i class="fas fa-database"></i>
                        Repositories
                    </a>
                    <a href="#">
                        <i class="fas fa-box"></i>
                        Packages
                    </a>
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <i class="fas fa-copy"></i>
                        Pages
                    </a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            <a href="#">Page 1</a>
                        </li>
                        <li>
                            <a href="#">Page 2</a>
                        </li>
                        <li>
                            <a href="#">Page 3</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>

        <div class="content">
            @yield('main-content')
        </div>


    </div>
@endsection

resources/views/layouts/settings.blade.php
@extends('layouts.app')

@section('content')
    <div class="sidebar-wrapper">
        <!-- Sidebar  -->
        <nav class="sidebar">
            <ul class="list-unstyled components">
                <li>
                    <a href="{{ route('settings.profile') }}">
                        <i class="fas fa-user"></i> Profile
                    </a>
                    <a href="{{ route('settings.password') }}">
                        <i class="fas fa-key"></i> Password
                    </a>
                    <a href="{{ route('settings.security') }}">
                        <i class="fas fa-lock"></i> Security
                    </a>
                    <a href="#developer-submenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <i class="fas fa-laptop"></i> Developer settings
                    </a>
                    <ul class="collapse list-unstyled" id="developer-submenu">
                        <li>
                            <a href="{{ route('settings.access-tokens') }}">Personal Access Tokens</a>
                        </li>
                        <li>
                            <a href="{{ route('settings.applications') }}">Applications</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
        <div class="content">
            @yield('main-content')
        </div>
    </div>
@endsection